Repository DiaboloAB/RType, pull requests merged in 2024-11, with the labels that each got.

#141 merge(dev): merge netwInEcs into dev
  docs/rfc-53952.txt
  engine/include/common/ICppScript.hpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.cpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.hpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.cpp
  engine/libs/mlg/src/mlg/vector/vec3.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/Bullet.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/network/cppScripts/ClientRedirect.hpp
  engine/src/common/network/cppScripts/RoomRedirect.hpp
  engine/src/common/network/cppScripts/redirect/ConnectionRedirect.hpp
  engine/src/common/network/cppScripts/redirect/EntityRedirect.hpp
  engine/src/common/systems/DrawableSystem.hpp
Labels: enhancement

#145 merge(dev): merge netwInEcs into dev
  README.md
  engine/include/common/ICppScript.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/Bullet.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/cppScripts/MoveLaser.hpp
  engine/src/common/cppScripts/MovePlayer.hpp
  engine/src/common/cppScripts/RedShip.hpp
  engine/src/common/cppScripts/Terrain.hpp
  engine/src/common/network/cppScripts/redirect/EntityRedirect.hpp
  engine/src/common/systems/DrawableSystem.hpp
  engine/src/sceneManager/createEntity.cpp
Labels: documentation, enhancement, fix

#146 merge(dev) merge branch menu into dev
  engine/include/common/ICppScript.hpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/SYSTEMLIST.hpp
  engine/src/common/components/components.hpp
  engine/src/common/components/fromJson.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/GameManager.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/systems/AudioSystem.hpp
  engine/src/common/systems/CppScriptsSystem.hpp
  engine/src/sceneManager/SceneManager.cpp
  engine/src/sceneManager/SceneManager.hpp
  rtypeClient/assets/scenes/menu.json
  rtypeClient/assets/scenes/settings.json
  rtypeClient/assets/sounds/bip.ogg
  rtypeClient/assets/sounds/mainTrack.ogg
  rtypeClient/assets/sounds/menu.ogg
Labels: enhancement

#149 merge(dev): feature/linkServer into dev
  engine/libs/dimension/src/dimension/endpoint/server/AServer.cpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.hpp
  engine/libs/sdl_lib/src/sdl_lib/RenderSystemSDL.cpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/BigHeadRobot.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/cppScripts/Turret.hpp
  engine/src/common/network/cppScripts/ComServer.hpp
  engine/src/common/systems/DrawableSystem.hpp
  rtypeClient/assets/scenes/menu.json
Labels: enhancement, fix

#150 merge
  engine/src/common/cppScripts/BigHeadRobot.hpp
  engine/src/common/cppScripts/RedShip.hpp
  engine/src/common/cppScripts/Turret.hpp
Labels: fix

#151 merge(dev): feature/roomRecep into dev
  engine/libs/dimension/src/dimension/endpoint/room/Room.cpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.hpp
  engine/src/common/network/cppScripts/RoomRedirect.hpp
  engine/src/common/network/cppScripts/redirect/EntityRedirect.hpp
Labels: enhancement

#153 merge(dev): feat/script_network_client into dev
  engine/libs/dimension/src/dimension/packet/basics/MoveEntity.cpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/cppScripts/Ally.hpp
  engine/src/common/cppScripts/MovePlayer.hpp
  engine/src/common/network/cppScripts/RoomRedirect.hpp
  engine/src/common/network/cppScripts/redirect/ConnectionRedirect.hpp
  engine/src/common/network/cppScripts/redirect/EntityRedirect.hpp
  engine/src/common/network/cppScripts/redirect/EventRedirect.hpp
  engine/src/common/systems/AudioSystem.hpp
  engine/src/gameContext/GameContext.hpp
  engine/src/utils/GetCppScript.hpp
  rtypeClient/assets/scenes/prefabs/GreyShip.json
  rtypeClient/assets/scenes/prefabs/RedShip.json
  rtypeClient/assets/scenes/prefabs/Turret.json
  rtypeClient/assets/scenes/prefabs/ally.json
  rtypeClient/assets/scenes/prefabs/player.json
  rtypeClient/assets/scenes/scenes2.json
  rtypeServer/assets/scenes/prefabs/GreyShip.json
  rtypeServer/assets/scenes/prefabs/RedShip.json
  rtypeServer/assets/scenes/prefabs/ally.json
  rtypeServer/assets/scenes/prefabs/player.json
Labels: enhancement

#154 merge(dev) merrge test/networkCo into dev
  engine/include/IRuntime/IRuntime.hpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.hpp
  engine/src/NullRuntime/NullRuntime.hpp
  engine/src/RTypeEngine.cpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/network/systems/roomSystem.hpp
  engine/src/common/systems/AudioSystem.hpp
  engine/src/common/systems/CppScriptsSystem.hpp
  engine/src/common/systems/ScriptsSystem.hpp
  engine/src/sceneManager/SceneManager.cpp
  engine/src/sceneManager/SceneManager.hpp
  engine/src/sceneManager/createEntity.cpp
  engine/src/system/ISystem.hpp
  engine/src/system/SystemManager.cpp
  engine/src/system/SystemManager.hpp
Labels: enhancement

#160 merge(dev): netwDoxy into dev
  engine/src/common/network/cppScripts/redirect/EventRedirect.hpp
Labels: documentation

#164 merge(dev): merge build/windows into dev
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/cppScripts/Turret.hpp
Labels: build
