Repository DiaboloAB/RType, pull requests merged in 2024-10, with the labels that each got.

#116 merge(dev) merge branch 106 feat json component interface into dev
  .github/workflows/ci.yml
  assets/game.json
  assets/scenes/scenesTest.json
  assets/scripts/player.lua
  engine/src/RTypeEngine.cpp
  engine/src/RTypeEngine.hpp
  engine/src/common/components.hpp
  engine/src/common/fromJson.hpp
  engine/src/common/scriptsComponent.hpp
  engine/src/gameContext/GameContext.cpp
  engine/src/gameContext/GameContext.hpp
  engine/src/lua/getKey.cpp
  engine/src/sceneManager/SceneManager.cpp
  engine/src/sceneManager/SceneManager.hpp
  engine/src/sceneManager/createEntity.cpp
Labels: enhancement

#121 Fea tdefine base components
  CMakeLists.txt
  assets/scripts/player.lua
  conanfile.py
  engine/CMakeLists.txt
  engine/src/RTypeEngine.cpp
  engine/src/RTypeEngine.hpp
  engine/src/addSystems.cpp
  engine/src/common/components.hpp
  engine/src/common/scriptsComponent.hpp
  engine/src/common/systems/DrawableSystem.hpp
  engine/src/common/systems/HealthSystem.hpp
  engine/src/common/systems/ScrollSystem.hpp
  engine/src/common/systems/SpriteSystem.hpp
  engine/src/common/systems/TimerSystem.hpp
  engine/src/common/systems/forward.hpp
  engine/src/gameContext/GameContext.cpp
  engine/src/gameContext/GameContext.hpp
  engine/src/sceneManager/SceneManager.cpp
  engine/src/sceneManager/SceneManager.hpp
  engine/src/sceneManager/addScriptsToEntity.cpp
  engine/src/sceneManager/createEntity.cpp
  engine/src/sceneManager/initComponentCreators.cpp
  engine/src/sceneManager/initCppScriptCreators.cpp
  engine/src/utils/DLLoader.hpp
  engine/src/utils/LoadLibs.cpp
  engine/src/utils/LoadLibs.hpp
  libs/sfml/CMakeLists.txt
  libs/sfml/src/IRuntime.hpp
  libs/sfml/src/KeyCode.hpp
  libs/sfml/src/RenderSystemSFML.cpp
  libs/sfml/src/RenderSystemSFML.hpp
  libs/sfml/src/vec3.hpp
  libs/sfml/src/vec4.hpp
Labels: enhancement

#124 merge (dev): merge feature/fix_sfml_key branch into dev
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
Labels: enhancement

#125 Fea tdefine base components
  .gitignore
  build.bat
  engine/src/common/components.hpp
  rtypeClient/CMakeLists.txt
  rtypeServer/CMakeLists.txt
Labels: build

#123 merge(dev) feature/dimNewE into dev
  docs/rfc-53952.txt
  engine/CMakeLists.txt
  engine/libs/dimension/CMakeLists.txt
  engine/libs/dimension/src/dimension/endpoint/AEndpoint.cpp
  engine/libs/dimension/src/dimension/endpoint/AEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/IEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/ResendTimer.hpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.cpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.hpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.cpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.hpp
  engine/libs/dimension/src/dimension/packet/APacket.cpp
  engine/libs/dimension/src/dimension/packet/APacket.hpp
  engine/libs/dimension/src/dimension/packet/PacketFactory.cpp
  engine/libs/dimension/src/dimension/packet/PacketFactory.hpp
  engine/libs/dimension/src/dimension/packet/PacketManager.cpp
  engine/libs/dimension/src/dimension/packet/PacketManager.hpp
  engine/libs/dimension/src/dimension/packet/basics/AdiosServer.cpp
  engine/libs/dimension/src/dimension/packet/basics/AdiosServer.hpp
  engine/libs/dimension/src/dimension/packet/basics/ClientEvent.cpp
  engine/libs/dimension/src/dimension/packet/basics/ClientEvent.hpp
  engine/libs/dimension/src/dimension/packet/basics/ClientEventType.hpp
  engine/libs/dimension/src/dimension/packet/basics/CreateEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/CreateEntity.hpp
  engine/libs/dimension/src/dimension/packet/basics/DestroyEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/DestroyEntity.hpp
  engine/libs/dimension/src/dimension/packet/basics/HiClient.cpp
  engine/libs/dimension/src/dimension/packet/basics/HiClient.hpp
  engine/libs/dimension/src/dimension/packet/basics/HiServer.cpp
  engine/libs/dimension/src/dimension/packet/basics/HiServer.hpp
  engine/libs/dimension/src/dimension/packet/basics/MoveEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/MoveEntity.hpp
  engine/libs/dimension/src/dimension/packet/basics/PacketValidation.cpp
  engine/libs/dimension/src/dimension/packet/basics/PacketValidation.hpp
  engine/libs/dimension/src/dimension/packet/basics/Ping.cpp
  engine/libs/dimension/src/dimension/packet/basics/Ping.hpp
  engine/libs/dimension/src/dimension/packet/basics/UpdateEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/UpdateEntity.hpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/src/RTypeEngine.cpp
  engine/src/common/components.hpp
  engine/src/common/fromJsonNetwork.hpp
  engine/src/common/network/components/networkComp.hpp
  engine/src/common/network/cppScripts/ComServer.hpp
  engine/src/gameContext/GameContext.hpp
  engine/src/sceneManager/createEntity.cpp
  engine/src/sceneManager/initCppScriptCreators.cpp
  rtypeClient/assets/scenes/scenesTest.json
  rtypeServer/CMakeLists.txt
  rtypeServer/src/main.cpp
  rtypeServer/src/server/ArgParser.cpp
  rtypeServer/src/server/ArgParser.hpp
  rtypeServer/src/server/Instance.cpp
  rtypeServer/src/server/MainServer.cpp
  rtypeServer/src/server/MainServer.hpp
Labels: enhancement, build

#126 merge(dev): feature/dimNewE into dev
  docs/rfc-53952.txt
  engine/libs/dimension/CMakeLists.txt
  engine/libs/dimension/src/dimension/Logger.hpp
  engine/libs/dimension/src/dimension/endpoint/AEndpoint.cpp
  engine/libs/dimension/src/dimension/endpoint/AEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/IEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/ResendTimer.hpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.cpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.hpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.cpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.hpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.cpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.hpp
  engine/libs/dimension/src/dimension/packet/basics/UpdateEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/UpdateEntity.hpp
  engine/src/common/network/components/networkComp.hpp
  engine/src/common/network/cppScripts/ComServer.hpp
  rtypeServer/CMakeLists.txt
  rtypeServer/src/server/Instance.cpp
  rtypeServer/src/server/MainServer.cpp
  rtypeServer/src/server/MainServer.hpp
  rtypeServer/src/server/parser/ArgParser.cpp
  rtypeServer/src/server/parser/ArgParser.hpp
  rtypeServer/src/server/rooms/GameInstance.hpp
  rtypeServer/src/server/rooms/RoomManager.cpp
  rtypeServer/src/server/rooms/RoomManager.hpp
  rtypeServer/src/server/rooms/RoomState.hpp
Labels: documentation, enhancement, build

#130 merge(dev) merge prefab system into dev
  engine/CMakeLists.txt
  engine/include/common/ICppScript.hpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/src/RTypeEngine.cpp
  engine/src/RTypeEngine.hpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/FROMJSON.hpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/SYSTEMLIST.hpp
  engine/src/common/components.hpp
  engine/src/common/components/animations/Animation.cpp
  engine/src/common/components/animations/Animation.hpp
  engine/src/common/components/animations/AnimationList.cpp
  engine/src/common/components/animations/AnimationList.hpp
  engine/src/common/components/components.hpp
  engine/src/common/components/fromJson.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/AnimPlayer.hpp
  engine/src/common/cppScripts/AnimThruster.hpp
  engine/src/common/cppScripts/Credit.hpp
  engine/src/common/cppScripts/EnemyFactory.hpp
  engine/src/common/cppScripts/GameManager.hpp
  engine/src/common/cppScripts/HelloWorld.hpp
  engine/src/common/cppScripts/Laser.hpp
  engine/src/common/cppScripts/MoveAlly.hpp
  engine/src/common/cppScripts/MovePlayer.hpp
  engine/src/common/cppScripts/MoveThruster.hpp
  engine/src/common/cppScripts/NetworkMovePlayer.hpp
  engine/src/common/cppScripts/PlayerShoot.hpp
  engine/src/common/cppScripts/RedShipScript.hpp
  engine/src/common/network/components/fromJsonNetwork.hpp
  engine/src/common/network/components/networkComp.hpp
  engine/src/common/network/cppScripts/ComServer.hpp
  engine/src/common/systems/CppScriptsSystem.hpp
  engine/src/common/systems/ScriptsSystem.hpp
  engine/src/gameContext/GameContext.hpp
  engine/src/lua/getKey.cpp
  engine/src/lua/luaBindings.hpp
  engine/src/sceneManager/SceneManager.cpp
  engine/src/sceneManager/SceneManager.hpp
  engine/src/sceneManager/addScriptsToEntity.cpp
  engine/src/sceneManager/createEntity.cpp
  engine/src/sceneManager/initComponentCreators.cpp
  engine/src/sceneManager/initCppScriptCreators.cpp
Labels: enhancement

#132 merge(dev): feature/netwInEcs into dev
  engine/include/common/KeyCode.hpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.cpp
  engine/libs/sdl_lib/src/sdl_lib/RenderSystemSDL.cpp
  engine/libs/sdl_lib/src/sdl_lib/RenderSystemSDL.hpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.hpp
  engine/src/RTypeEngine.cpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/SYSTEMLIST.hpp
  engine/src/common/cppScripts/HelloWorld.hpp
  engine/src/common/network/components/fromJsonNetwork.hpp
  engine/src/common/network/components/networkComp.hpp
  engine/src/common/network/systems/roomSystem.hpp
  engine/src/sceneManager/SceneManager.hpp
  engine/src/sceneManager/createEntity.cpp
  engine/src/utils/random.hpp
  rtypeServer/assets/scenes/prefabs/ally.json
  rtypeServer/assets/scenes/prefabs/player.json
  rtypeServer/src/server/rooms/RoomManager.cpp
Labels: enhancement

#135 merge(dev) merge physic branch into dev
  engine/include/common/ICppScript.hpp
  engine/libs/mlg/src/mlg/vector/vec4.hpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/SYSTEMLIST.hpp
  engine/src/common/components/components.hpp
  engine/src/common/components/fromJson.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/cppScripts/HelloWorld.hpp
  engine/src/common/systems/PhysicsCollisionSystem.hpp
  rtypeClient/assets/game.json
  rtypeClient/assets/scenes/credits.json
  rtypeClient/assets/scenes/scenes1.json
  rtypeClient/assets/scenes/scenesTest2.json
Labels: enhancement

#137 merge(dev) merge Feature/menu into dev
  engine/include/common/ICppScript.hpp
  engine/include/common/KeyCode.hpp
  engine/libs/mobs/src/mobs/mobs.hpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.hpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/FROMJSON.hpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/SYSTEMLIST.hpp
  engine/src/common/components/components.hpp
  engine/src/common/components/scriptsComponent.hpp
  engine/src/common/components/uiComponents.hpp
  engine/src/common/components/uiFromJson.hpp
  engine/src/common/cppScripts/Menu.hpp
  engine/src/common/systems/DrawableSystem.hpp
  engine/src/sceneManager/createEntity.cpp
  rtypeClient/assets/fonts/r-type.ttf
  rtypeClient/assets/game.json
  rtypeClient/assets/graphics/keyboard.png
  rtypeClient/assets/scenes/menu.json
  rtypeClient/assets/scenes/settings.json
Labels: enhancement

#136 merge(dev): feature/netwInEcs into dev
  engine/libs/dimension/src/dimension/endpoint/AEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/IEndpoint.hpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.cpp
  engine/libs/dimension/src/dimension/endpoint/client/Client.hpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.cpp
  engine/libs/dimension/src/dimension/endpoint/room/Room.hpp
  engine/libs/dimension/src/dimension/endpoint/server/AServer.cpp
  engine/libs/dimension/src/dimension/packet/APacket.hpp
  engine/libs/dimension/src/dimension/packet/PacketManager.cpp
  engine/libs/dimension/src/dimension/packet/PacketManager.hpp
  engine/libs/dimension/src/dimension/packet/basics/AdiosServer.cpp
  engine/libs/dimension/src/dimension/packet/basics/ClientEventType.hpp
  engine/libs/dimension/src/dimension/packet/basics/DestroyEntity.cpp
  engine/libs/dimension/src/dimension/packet/basics/HiClient.cpp
  engine/libs/dimension/src/dimension/packet/basics/HiServer.cpp
  engine/libs/dimension/src/dimension/packet/basics/PacketValidation.cpp
  engine/libs/dimension/src/dimension/packet/basics/Ping.cpp
  engine/libs/dimension/src/dimension/packet/basics/UpdateEntity.cpp
  engine/libs/sfml_lib/src/sfml_lib/RenderSystemSFML.cpp
  engine/src/common/COMPONENTLIST.hpp
  engine/src/common/SCRIPTLIST.hpp
  engine/src/common/components/animations/Animation.hpp
  engine/src/common/components/animations/AnimationList.hpp
  engine/src/common/components/components.hpp
  engine/src/common/network/components/fromJsonNetwork.hpp
  engine/src/common/network/components/networkComp.hpp
  engine/src/common/network/cppScripts/ClientRedirect.hpp
  engine/src/common/network/cppScripts/ComServer.hpp
  engine/src/common/network/cppScripts/RoomRedirect.hpp
  engine/src/common/network/cppScripts/redirect/ConnectionRedirect.hpp
  engine/src/common/network/cppScripts/redirect/EntityRedirect.hpp
  engine/src/common/network/cppScripts/redirect/UpdateRedirect.hpp
  engine/src/common/network/systems/roomSystem.hpp
  engine/src/common/systems/CppScriptsSystem.hpp
  engine/src/common/systems/PhysicsCollisionSystem.hpp
  rtypeClient/assets/scenes/menu.json
  rtypeClient/assets/scenes/scenesTest.json
  rtypeServer/assets/game.json
  rtypeServer/assets/scenes/prefabs/room.json
  rtypeServer/src/server/MainServer.cpp
  rtypeServer/src/server/MainServer.hpp
  rtypeServer/src/server/rooms/RoomManager.cpp
  rtypeServer/src/server/rooms/RoomManager.hpp
Labels: enhancement
